title: Janko's Blog
description: Sharing the wonders of Ruby

author:
  first_name: Janko
  last_name: Marohnić
  name: Janko Marohnić
  bio: Ruby-off-Rails evangelist, Roda & Sequel fan, Rails critic, author of [Shrine](https://shrinerb.com), [test.vim](https://github.com/janko/vim-test) and numerous other open source libraries.
  image: /images/me.jpg
  github: janko
  twitter: jankomarohnic
  email: janko@hey.com
  facebook: janko.marohnic

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

baseurl: ""
url: http://twin.github.io
repository: twin/twin.github.io

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/
  - scope:
      path: ""
      type: drafts
    values:
      layout: post

logo: /images/logo.png

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache
  - vendor

emoji:
  src: "/images"
